version: '3.7'

services:
  postgres:
    image: postgres:alpine3.20
    container_name: postgres
    volumes:
      - db:/var/lib/postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user
      - POSTGRES_DB=db-postgres
      - POSTGRES_HOST=database
    networks:
      - application-network

  application:
    build:
      context: .
    container_name: application
    ports:
      - 3001:3000
    depends_on:
      - postgres
    networks:
      - application-network

networks:
  application-network:
    driver: bridge

volumes:
  db:
